package com.amol.dynamodb.test.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName="users")
public class User {
	
	@DynamoDBHashKey(attributeName="userId")
	@DynamoDBAutoGeneratedKey
	private String userId;
	
	@DynamoDBAttribute(attributeName="userName")
	private String userName;
	
	@DynamoDBAttribute(attributeName="email")
	private String email;
	
	@DynamoDBAttribute(attributeName="contact")
	private String contact;
	
	@DynamoDBAttribute(attributeName="role")
	private Role role;

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getContact() {
		return contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}
	
	

}
